# agents/alert/main.py — Alert Agent
import os
import json
from uuid import uuid4
from datetime import datetime, timedelta

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from agents.base_agent import BaseFinanceAgent
from agents.alert.monitor import (
    check_overdue_invoices,
    check_unmatched_reconciliation,
    check_low_runway,
    check_unusual_transactions,
    check_tax_deadlines,
)
from agents.tax_compliance.calendar_mcp import CalendarMCPClient
from agents.invoice_parser.gmail_mcp import GmailMCPClient
from shared.models import AgentTask, AgentResult


class AlertAgent(BaseFinanceAgent):
    AGENT_NAME = "alert_agent"
    SUBSCRIBE_TOPIC = "finance.alert"
    SYSTEM_PROMPT = "You are FinancePilot Alert Agent."

    def __init__(self):
        super().__init__()
        self.calendar = CalendarMCPClient()
        self.gmail = GmailMCPClient()

    async def process_task(self, task: AgentTask) -> AgentResult:
        """Monitor thresholds, create alerts, send notifications."""
        payload = task.payload
        action = task.action
        all_alerts = []

        if action == "unmatched_invoice":
            # Specific alert from Reconciliation Agent
            invoice_id = payload.get("invoice_id")
            all_alerts.append({
                "alert_type": "unmatched_reconciliation",
                "severity": "medium",
                "message": f"Invoice {invoice_id} could not be matched to any bank transaction.",
                "related_invoice_id": invoice_id,
            })
        else:
            # Full scan
            # 1. Check overdue invoices
            inv_resp = self.supabase.table("invoices").select("*").eq(
                "company_id", task.company_id
            ).neq("status", "reconciled").execute()
            invoices = inv_resp.data or []
            all_alerts.extend(check_overdue_invoices(invoices))
            all_alerts.extend(check_unmatched_reconciliation(invoices))

            # 2. Check cash runway
            forecast_resp = self.supabase.table("forecasts").select("*").eq(
                "company_id", task.company_id
            ).order("generated_at", desc=True).limit(1).execute()
            if forecast_resp.data:
                runway_alert = check_low_runway(forecast_resp.data[0])
                if runway_alert:
                    all_alerts.append(runway_alert)

            # 3. Check unusual transactions
            date_from = (datetime.utcnow() - timedelta(days=90)).strftime("%Y-%m-%d")
            txn_resp = self.supabase.table("bank_transactions").select("*").eq(
                "company_id", task.company_id
            ).gte("date", date_from).execute()
            all_alerts.extend(check_unusual_transactions(txn_resp.data or []))

            # 4. Check tax deadlines
            tax_resp = self.supabase.table("tax_records").select("*").eq(
                "company_id", task.company_id
            ).neq("status", "filed").execute()
            all_alerts.extend(check_tax_deadlines(tax_resp.data or []))

        # Process each alert
        saved_alerts = []
        for alert_data in all_alerts:
            alert_record = {
                "id": str(uuid4()),
                "company_id": task.company_id,
                "alert_type": alert_data["alert_type"],
                "severity": alert_data["severity"],
                "message": alert_data["message"],
                "related_invoice_id": alert_data.get("related_invoice_id"),
            }

            # Create Calendar event for critical alerts
            if alert_data["severity"] in ("critical", "high"):
                try:
                    event = await self.calendar.create_event(
                        summary=f"⚠️ FinancePilot Alert: {alert_data['alert_type']}",
                        description=alert_data["message"],
                        start_date=datetime.utcnow().strftime("%Y-%m-%d"),
                        reminders=[1],
                    )
                    alert_record["calendar_event_id"] = event.get("id")
                except Exception as e:
                    self.logger.warning(f"Failed to create Calendar alert: {e}")

            # Send email for critical alerts
            if alert_data["severity"] == "critical":
                try:
                    await self.gmail.send_email(
                        to="alerts@company.com",
                        subject=f"🚨 FinancePilot Critical Alert: {alert_data['alert_type']}",
                        body=f"<div style='font-family: sans-serif; padding: 20px;'>"
                             f"<h2 style='color: #c62828;'>⚠️ Critical Financial Alert</h2>"
                             f"<p>{alert_data['message']}</p>"
                             f"<p style='color: #666; font-size: 12px;'>Generated by FinancePilot Alert Agent</p></div>",
                        html=True,
                    )
                    alert_record["email_sent_at"] = datetime.utcnow().isoformat()
                except Exception as e:
                    self.logger.warning(f"Failed to send alert email: {e}")

            # Save to Supabase
            try:
                self.supabase.table("alerts").insert(alert_record).execute()
                saved_alerts.append(alert_record)
            except Exception as e:
                self.logger.error(f"Failed to save alert: {e}")

        return AgentResult(
            task_id=task.task_id,
            session_id=task.session_id,
            agent_name=self.AGENT_NAME,
            status="success",
            result={
                "alerts_generated": len(all_alerts),
                "critical": sum(1 for a in all_alerts if a["severity"] == "critical"),
                "high": sum(1 for a in all_alerts if a["severity"] == "high"),
                "medium": sum(1 for a in all_alerts if a["severity"] == "medium"),
                "alerts": all_alerts,
            },
            tokens_used=0,
        )


if __name__ == "__main__":
    agent = AlertAgent()
    agent.start_subscriber()
