# agents/report/templates.py — Email report HTML templates

def board_report_template(data: dict) -> str:
    """Generate HTML email template for monthly board report."""
    return f"""
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1a1a2e; margin: 0; padding: 0; background: #f8f9fa; }}
  .container {{ max-width: 700px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
  .header {{ background: linear-gradient(135deg, #0f3460 0%, #16213e 100%); color: white; padding: 32px; }}
  .header h1 {{ margin: 0; font-size: 28px; font-weight: 700; }}
  .header p {{ margin: 8px 0 0 0; opacity: 0.85; font-size: 14px; }}
  .content {{ padding: 32px; }}
  .metric-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 24px 0; }}
  .metric {{ background: #f8f9fa; border-radius: 10px; padding: 20px; border-left: 4px solid #0f3460; }}
  .metric .label {{ font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #666; }}
  .metric .value {{ font-size: 24px; font-weight: 700; color: #0f3460; margin: 4px 0; }}
  .metric .change {{ font-size: 13px; color: #27ae60; }}
  .metric .change.negative {{ color: #e74c3c; }}
  table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
  th {{ background: #f1f3f5; padding: 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; border-bottom: 2px solid #dee2e6; }}
  td {{ padding: 12px; border-bottom: 1px solid #f1f3f5; font-size: 14px; }}
  .status {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }}
  .status-healthy {{ background: #e8f5e9; color: #2e7d32; }}
  .status-warning {{ background: #fff3e0; color: #ef6c00; }}
  .status-critical {{ background: #fce4ec; color: #c62828; }}
  .section {{ margin: 28px 0; }}
  .section h2 {{ font-size: 18px; color: #0f3460; border-bottom: 2px solid #e8eaf6; padding-bottom: 8px; }}
  .footer {{ background: #f8f9fa; padding: 20px 32px; font-size: 12px; color: #999; text-align: center; }}
  .runway-bar {{ height: 8px; border-radius: 4px; background: #e8eaf6; margin: 8px 0; overflow: hidden; }}
  .runway-fill {{ height: 100%; border-radius: 4px; transition: width 0.3s; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 FinancePilot Monthly Report</h1>
    <p>{data.get('company_name', 'Your Company')} · {data.get('period', 'This Month')}</p>
  </div>
  <div class="content">
    <div class="section">
      <h2>Executive Summary</h2>
      <p>{data.get('executive_summary', 'Financial summary for the reporting period.')}</p>
    </div>

    <div class="metric-grid">
      <div class="metric">
        <div class="label">Revenue</div>
        <div class="value">{data.get('currency', 'SGD')} {data.get('revenue', 0):,.2f}</div>
        <div class="change">{data.get('revenue_change', '+0%')}</div>
      </div>
      <div class="metric">
        <div class="label">Net Profit</div>
        <div class="value">{data.get('currency', 'SGD')} {data.get('net_profit', 0):,.2f}</div>
        <div class="change">{data.get('profit_change', '+0%')}</div>
      </div>
      <div class="metric">
        <div class="label">Cash Balance</div>
        <div class="value">{data.get('currency', 'SGD')} {data.get('cash_balance', 0):,.2f}</div>
      </div>
      <div class="metric">
        <div class="label">Cash Runway</div>
        <div class="value">{data.get('runway_months', 'N/A')} months</div>
      </div>
    </div>

    <div class="section">
      <h2>Top 5 Vendors</h2>
      <table>
        <thead><tr><th>Vendor</th><th>Amount</th><th>Status</th></tr></thead>
        <tbody>
          {''.join(f"<tr><td>{v.get('name','')}</td><td>{data.get('currency','SGD')} {v.get('amount',0):,.2f}</td><td><span class='status status-healthy'>{v.get('status','Paid')}</span></td></tr>" for v in data.get('top_vendors', [])[:5])}
        </tbody>
      </table>
    </div>

    <div class="section">
      <h2>90-Day Forecast</h2>
      <p>{data.get('forecast_summary', 'Cash flow projections for the next 90 days.')}</p>
    </div>
  </div>
  <div class="footer">
    Generated by FinancePilot AI · {data.get('generated_at', '')} · Confidential
  </div>
</div>
</body>
</html>"""


def daily_digest_template(data: dict) -> str:
    """Generate HTML template for daily financial digest."""
    return f"""
<!DOCTYPE html>
<html>
<body style="font-family: 'Segoe UI', sans-serif; background: #f8f9fa; padding: 20px;">
<div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; padding: 32px; box-shadow: 0 2px 12px rgba(0,0,0,0.06);">
  <h1 style="color: #0f3460; font-size: 22px;">📋 Daily Financial Digest</h1>
  <p style="color: #666; font-size: 14px;">{data.get('date', 'Today')}</p>

  <div style="margin: 20px 0; padding: 16px; background: #f0f4ff; border-radius: 8px;">
    <strong>Key Numbers</strong>
    <ul style="margin: 8px 0; padding-left: 20px; color: #333;">
      <li>New invoices: {data.get('new_invoices', 0)}</li>
      <li>Reconciled: {data.get('reconciled', 0)}</li>
      <li>Pending review: {data.get('pending_review', 0)}</li>
      <li>Active alerts: {data.get('active_alerts', 0)}</li>
    </ul>
  </div>

  {'<div style="margin: 20px 0; padding: 16px; background: #fff3e0; border-radius: 8px; border-left: 4px solid #ff9800;"><strong>⚠️ Action Required</strong><p style="margin: 8px 0; font-size: 14px;">' + data.get('action_required', '') + '</p></div>' if data.get('action_required') else ''}

  <p style="font-size: 12px; color: #999; margin-top: 24px;">FinancePilot AI · Automated digest</p>
</div>
</body>
</html>"""
